### ISSUE TITLE
SonarLint Check

### ISSUE THREAD

**Issue by burkodigergely** [BME-MIT-IET/iet-hf2021-integracios-hf-csapat#12]
Check the whole project with the SonarLint scaning tool and examine the result, fixing the errors given by SonarLint. If it is not considered as an error than write a report why it is not an error

**Comment by AkosUzonyi** [comment]
I've reviewed the pull request, and commented where I didn't think SonarLint's warnings were actually a problem. If you agree, please revert those changes, and update the pull request.
